### ISSUE TITLE
Is get-user-code-from-github.js working as intended?

### ISSUE THREAD

**Issue by Marak** [JavascriptBattle/javascript-battle-webworkers#102] opened 2014-10-15 07:32 UTC
I took a cursory look over `get-user-code-from-github.js` file and it appears there may be some uncaught callbacks / promises.

I'm not 100% on promises, but I think there might be a missing then statement or use of async iterator for iterating over users array.

**Comment by forrestbthomas** [comment] 2014-10-15 16:19
From all appearances, this script seems to be working fine. The code we are pulling matches the users we have stored in our DB. I'll take a look through it again, though. Thanks!

**Comment by gjtrowbridge** [comment] 2015-01-12 02:43
I believe this is working as intended, so I'll close this.  If you see anything odd or your hero code doesn't appear to be updating day-to-day, let us know!

**Closed as completed by gjtrowbridge** 2015-01-12 02:43 UTC
